image: google/cloud-sdk:slim

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  REGION: us-central1
  REPO_NAME: gits-billing-fe
  IMAGE: $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$CLOUD_RUN_SERVICE_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev

deploy:
  stage: deploy
  script:
    - |
      docker build \
        --build-arg NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
        -t $IMAGE .
    - docker push $IMAGE
    - |
      gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
        --image=$IMAGE \
        --platform=managed \
        --region=$REGION \
        --allow-unauthenticated \
        --port=3000
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
