image: google/cloud-sdk:slim

variables:
  REGION: asia-southeast2
  REPO_NAME: gits-billing-fe
  PROD_SERVICE_NAME: $CLOUD_RUN_SERVICE_NAME
  STAGING_SERVICE_NAME: $STAGING_CLOUD_RUN_SERVICE_NAME

stages:
  - deploy

before_script:
  - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
  - gcloud auth activate-service-account --key-file gcp-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev

deploy_staging:
  stage: deploy
  tags:
    - gits-shell
  only:
    - staging
  script:
    - export IMAGE=$REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$STAGING_SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - |
      docker build \
        --build-arg NEXT_PUBLIC_SUPABASE_URL=$STAGING_NEXT_PUBLIC_SUPABASE_URL \
        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$STAGING_NEXT_PUBLIC_SUPABASE_ANON_KEY \
        --build-arg NEXT_PUBLIC_BASE_API_URL=$STAGING_NEXT_PUBLIC_BASE_API_URL \
        --build-arg NEXT_PUBLIC_AGENT_API_URL=$STAGING_NEXT_PUBLIC_AGENT_API_URL \
        --build-arg NEXT_PUBLIC_AGENT_API_URL=$NEXT_PUBLIC_N8N_WEBHOOK_CONTRACT \
        -t $IMAGE .
    - docker push $IMAGE
    - |
      gcloud run deploy $STAGING_SERVICE_NAME \
        --image=$IMAGE \
        --platform=managed \
        --region=$REGION \
        --allow-unauthenticated \
        --port=3000

deploy_production:
  stage: deploy
  tags:
    - gits-shell
  only:
    - production
  script:
    - export IMAGE=$REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$PROD_SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    - |
      docker build \
        --build-arg NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
        --build-arg NEXT_PUBLIC_BASE_API_URL=$NEXT_PUBLIC_BASE_API_URL \
        --build-arg NEXT_PUBLIC_AGENT_API_URL=$NEXT_PUBLIC_AGENT_API_URL \
        --build-arg NEXT_PUBLIC_AGENT_API_URL=$NEXT_PUBLIC_N8N_WEBHOOK_CONTRACT \
        -t $IMAGE .
    - docker push $IMAGE
    - |
      gcloud run deploy $PROD_SERVICE_NAME \
        --image=$IMAGE \
        --platform=managed \
        --region=$REGION \
        --allow-unauthenticated \
        --port=3000
